# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftTargetVersion = 1.21.1
minecraftVersion=1.21.1
yarnMappings=1.21.1+build.3
loaderVersion=0.16.7

kotlin.code.style = official
systemProp.kotlinVersion = 2.4.0
fabricKotlinVersion = 1.13.12+kotlin.2.4.0

# Mod Properties
modVersion = 1.14.0
mavenGroup = io.sc3

# Dependencies
# check this on https://fabricmc.net/develop
fabricVersion=0.106.0+1.21.1

ccVersion = 1.119.0
ccMcVersion = 1.21.1
ccTargetVersion = >=1.119.0

nightConfigVersion = 3.6.5
clothConfigVersion = 15.0.140
clothApiVersion = 4.0.65
modMenuVersion = 11.0.3

trinketsVersion = 3.10.0
cardinalComponentsVersion = 6.1.1

scLibraryVersion = 1.10.4
scTextVersion = 1.9.0
fabricPermissionsApiVersion = 0.3.1

kotlinSerializationVersion = 1.4.0
annotationsVersion = 23.0.0

figuraVersion = 0.1.5+1.21.1
