# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftTargetVersion = 1.20.x
minecraftVersion = 1.20.1
yarnMappings = 1.20.1+build.10
loaderVersion = 0.19.2

kotlin.code.style = official
systemProp.kotlinVersion = 2.1.20
fabricKotlinVersion = 1.13.2+kotlin.2.1.20

# Mod Properties
modVersion = 1.13.4
mavenGroup = io.sc3

# Dependencies
# check this on https://fabricmc.net/develop
fabricVersion = 0.92.8+1.20.1

ccVersion = 1.117.0
ccMcVersion = 1.20.1
ccTargetVersion = >=1.117.0

nightConfigVersion = 3.6.5
clothConfigVersion = 11.1.118
clothApiVersion = 4.0.65
modMenuVersion = 7.0.1

trinketsVersion = 3.7.0
cardinalComponentsVersion = 5.1.0
figuraVersion = 0.1.5+1.20.1

scLibraryVersion = 1.6.2
scTextVersion = 1.6.0
# do not pull 0.3.3, bad transitive dep
fabricPermissionsApiVersion = 0.3.1

kotlinSerializationVersion = 1.4.0
annotationsVersion = 23.0.0
